/*
ALTER TABLE USUARIO DROP FOREIGN KEY FK_NOME_GRUPO_USUARIO;
ALTER TABLE PARTICIPACAO  DROP FOREIGN KEY  FK_NOME_GRUPO_PARTICIPACAO;
ALTER TABLE PARTICIPACAO DROP FOREIGN KEY  FK_LOGIN_USUARIO_PARTICIPACAO;
ALTER TABLE PALPITE DROP FOREIGN KEY FK_LOGIN_USUSARIO_PALPITE;
ALTER TABLE PALPITE  DROP FOREIGN KEY FK_ESTADIO_DATA_HORA_JOGO_PALPITE;

DROP TABLE PARTICIPACAO;
DROP TABLE JOGO;
DROP TABLE EQUIPE;
DROP TABLE GRUPO;
DROP TABLE USUARIO;
DROP TABLE PALPITE;

*/

CREATE TABLE USUARIO
(
	LOGIN VARCHAR(20),
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	SENHA VARCHAR(10) NOT NULL,
	FOTO BLOB,
	DATA_HORA_ULT_LOGIN DATETIME,
	NOME_GRUPO_USUARIO VARCHAR (20),
	CONSTRAINT PK_LOGIN_USUARIO PRIMARY KEY (LOGIN)
);

CREATE TABLE PARTICIPACAO
(
	PONTOS_BOLAO INTEGER,
	NOME_GRUPO_PARTICIPACAO VARCHAR (20),
	LOGIN_USUARIO_PARTICIPACAO VARCHAR(20)
);

CREATE TABLE GRUPO
(
	NOME VARCHAR(20),
	CONSTRAINT PK_NOME_GRUPO PRIMARY KEY (NOME)
);

CREATE TABLE PALPITE
(
	GOLS_VISITANTE INTEGER,
	GOLS_ANFITRIA INTEGER,
	LOGIN_USUARIO_PALPITE VARCHAR (20),	
	ESTADIO_JOGO_PALPITE VARCHAR (20),
	DATA_HORA_JOGO_PALPITE DATETIME
);

CREATE TABLE JOGO
(
	ESTADIO VARCHAR(20),
	DATA_HORA DATETIME,
	RODADA INTEGER,
	GOLS_VISITANTE INTEGER,
	GOLS_ANFITRIA INTEGER,
	CONSTRAINT PK_ESTADIO_DATA_HORA_JOGO PRIMARY KEY (ESTADIO, DATA_HORA)
);

CREATE TABLE EQUIPE
(
	NOME VARCHAR(30),
	PONTOS INTEGER,
	GOLS_PRO INTEGER,
	GOLS_CONTRA INTEGER,
	CONSTRAINT PK_NOME_EQUIPE PRIMARY KEY (NOME)
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_NOME_GRUPO_USUARIO FOREIGN KEY (NOME_GRUPO_USUARIO) REFERENCES GRUPO(NOME);
ALTER TABLE PARTICIPACAO ADD CONSTRAINT FK_NOME_GRUPO_PARTICIPACAO FOREIGN KEY (NOME_GRUPO_PARTICIPACAO) REFERENCES GRUPO(NOME);
ALTER TABLE PARTICIPACAO ADD CONSTRAINT FK_LOGIN_USUARIO_PARTICIPACAO FOREIGN KEY (LOGIN_USUARIO_PARTICIPACAO) REFERENCES USUARIO (LOGIN);
ALTER TABLE PALPITE ADD CONSTRAINT FK_LOGIN_USUSARIO_PALPITE FOREIGN KEY (LOGIN_USUARIO_PALPITE) REFERENCES USUARIO (LOGIN);
ALTER TABLE PALPITE ADD CONSTRAINT FK_ESTADIO_DATA_HORA_JOGO_PALPITE FOREIGN KEY (ESTADIO_JOGO_PALPITE, DATA_HORA_JOGO_PALPITE) REFERENCES JOGO (ESTADIO, DATA_HORA);

